# Generated by Django 3.2.8 on 2022-11-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('editorial', models.CharField(max_length=200)),
                ('fechadelanzamiento', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('paginas', models.CharField(max_length=50)),
                ('portada', models.CharField(max_length=50)),
            ],
        ),
    ]
